config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :categories

  root 'storefront#all_categories'

  get 'categorical' => 'storefront#blogs_by_category'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :blogs

  has_attached_file :image, styles: { medium: "300x300>", thumb: "200x200" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :author, :entry, :link, :medialink, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name,:image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController

  def all_categories
    @categories = Category.all
  end

  def blogs_by_category
    @category = Category.find(params[:cat_id])
    @blogs = Blog.all
    @blogs_by_cat = []
    @blogs.each do |blog|
      if blog.category.id == params[:cat_id].to_i
        @blogs_by_cat.push(blog)
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def includespaces(text)
		text.gsub(/\n/, '<br>').html_safe
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :entry %>
    <%= f.text_area :entry %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :medialink %>
    <%= f.text_field :medialink %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.number_field :category_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="container">

<h1>Take Charge of Your Health</h1>

<div class="row">
	<% @blogs.each do |blog| %>
	<div class="col-sm-12 col-lg-6">
    <div class="panel panel-default">
			<div class="panel-heading">
				<h3><%= link_to blog.title, blog %></h3>
			</div>
			<div class="panel-body">
				by <%= blog.author %><br>
				<h6><i>Posted: <%= blog.created_at.strftime('%-m/%d/%Y at %I:%M%p') %></i></h6>
        <p><b><%= blog.category.name %></b></p>
			</div>
		</div>
	</div>
	<% end %>
</div>

<br>


<div>
<%= link_to 'New Blog Post', new_blog_path, class: "btn btn-primary" %>
</div>


</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
	<div class="panel-heading">
		<h2><%= @blog.title %></h2>
	</div>

	<div class="panel-body">
		<p><b><i><%= @blog.author %></p></b></i>
		<h6><i><%= time_ago_in_words(@blog.created_at) %> ago</i></h6>
		<br>

    <section class="row">
      <div class="col-sm-6 col-lg-6">
        <div class="flex-video widescreen"><iframe src="<%= @blog.medialink %>" frameborder="0" allowfullscreen=""></iframe></div>
      </div>
    </section>

		<p><%= includespaces(@blog.entry).html_safe %></p>
	</div>
</div>

<%= link_to 'Back', blogs_path %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <strong>Upload Product Image:</strong>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">

<h1>Take Charge of Your Health</h1>

<div class="row">
	<% @categories.each do |category| %>
	<div class="col-sm-12 col-med-6 col-lg-6">
    <div class="panel panel-default">
			<div class="panel-heading">
				<h3><%= link_to category.name, category %></h3>
			</div>
		</div>
	</div>
	<% end %>
</div>

<br>


<div>
<%= link_to 'New Category', new_category_path, class: "btn btn-primary" %>
</div>


</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/storefront/all_categories.html.erb
<div class="container">

<h1>Take Charge of Your Health</h1>

<div class="row">
	<% @categories.each do |cat| %>
	<div class="col-sm-6 col-lg-6">
    <div class="panel panel-default">
			<div class="panel-heading panel-height">
				 <h2><center><%= link_to cat.name, categorical_path(cat_id: cat.id) %></center></h2>
				 <center><%= image_tag cat.image.url(:thumb) %></center>
			</div>
		</div>
	</div>
	<% end %>
</div>

<br>


<div>
<%= link_to 'New Category', new_category_path, class: "btn btn-primary" %>
</div>


</div>

app/views/storefront/blogs_by_category.html.erb
<h3>All <%= @category.name %></h3>

<div class="row">
	<% @blogs_by_cat.each do |blog| %>
	<div class="col-sm-12 col-lg-6">
    <div class="panel panel-default">
			<div class="panel-heading">
				<h3><%= link_to blog.title, blog %></h3>
			</div>
			<div class="panel-body">
				by <%= blog.author %><br>
				<h6><i>Posted: <%= blog.created_at.strftime('%-m/%d/%Y at %I:%M%p') %></i></h6>
          <div class="span6">
            <div class="flex-video widescreen"><iframe src="<%= blog.medialink %>" frameborder="0" allowfullscreen=""></iframe></div>
          </div>
				<p><%= link_to "Read More", blog, class: "btn btn-info btn-block" %></p>
			</div>
		</div>
	</div>
	<% end %>
</div>